In [1]:
print("Kernel working correctly")

Kernel working correctly

## Importing necessary libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from imblearn.over_sampling import RandomOverSampler
sns.set(style="whitegrid")

import warnings
warnings.filterwarnings("ignore")

## Importing Dataset

In [3]:
df = pd.read_csv('data.csv')

In [4]:
df.head(10)

   id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
0   1    Male   44  ...                  26.0      217         1
1   2    Male   76  ...                  26.0      183         0
2   3    Male   47  ...                  26.0       27         1
3   4    Male   21  ...                 152.0      203         0
4   5  Female   29  ...                 152.0       39         0
5   6  Female   24  ...                 160.0      176         0
6   7    Male   23  ...                 152.0      249         0
7   8  Female   56  ...                  26.0       72         1
8   9  Female   24  ...                 152.0       28         0
9  10  Female   32  ...                 152.0       80         0

[10 rows x 12 columns]

### About the Data 


- **id**: Unique ID for the customer  
- **Gender**: Gender of the customer  
- **Age**: Age of the customer  
- **Driving_License**:  
  - `0`: Customer does **not** have a Driving License  
  - `1`: Customer **has** a Driving License  
- **Region_Code**: Unique code representing the customerâ€™s region  
- **Previously_Insured**:  
  - `1`: Customer **already has** Vehicle Insurance  
  - `0`: Customer **does not have** Vehicle Insurance  
- **Vehicle_Age**: Age of the vehicle (e.g., `< 1 Year`, `1-2 Year`, `> 2 Years`)  
- **Vehicle_Damage**:  
  - `1`: Customer's vehicle was **damaged** in the past  
  - `0`: Customer's vehicle was **not damaged** in the past  
- **Annual_Premium**: Annual premium amount the customer needs to pay  
- **Policy_Sales_Channel**: Anonymized code representing the sales channel (e.g., Agent, Phone, Email, In-person)  
- **Vintage**: Number of days the customer has been associated with the company  
- **Response**:  
  - `1`: Customer is **interested** in vehicle insurance  
  - `0`: Customer is **not interested**